"""
Privacy Policy Update for GenAI Content Safety Compliance
Updates the existing privacy policy to include GenAI safety measures
"""

def get_updated_privacy_policy_html():
    """
    Generate updated privacy policy HTML with GenAI content safety disclosures
    """
    return '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Privacy Policy - IELTS GenAI Prep</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            background-color: #f8f9fa;
        }
        .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem 0;
            text-align: center;
        }
        .content {
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
            background: white;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            margin-top: -1rem;
        }
        .section {
            margin-bottom: 2rem;
        }
        .section h3 {
            color: #667eea;
            border-bottom: 2px solid #667eea;
            padding-bottom: 0.5rem;
        }
        .safety-highlight {
            background: #e8f4f8;
            border-left: 4px solid #17a2b8;
            padding: 1rem;
            margin: 1rem 0;
            border-radius: 5px;
        }
        .back-btn {
            display: inline-block;
            margin-bottom: 1rem;
            color: #667eea;
            text-decoration: none;
            font-weight: 500;
        }
        .back-btn:hover {
            color: #764ba2;
        }
        .genai-section {
            background: #f0f8ff;
            border: 1px solid #b8daff;
            border-radius: 8px;
            padding: 1.5rem;
            margin: 1.5rem 0;
        }
        .genai-section h4 {
            color: #0056b3;
            margin-bottom: 1rem;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Privacy Policy</h1>
        <p>Your privacy and AI safety are our top priorities</p>
    </div>
    
    <div class="container">
        <div class="content">
            <a href="/" class="back-btn">← Back to Home</a>
            
            <div class="section">
                <h3>Last Updated: July 11, 2025</h3>
                <p>This Privacy Policy describes how IELTS GenAI Prep collects, uses, and protects your information when you use our AI-powered assessment services.</p>
            </div>
            
            <div class="genai-section">
                <h4>🤖 AI Content Safety and Privacy</h4>
                <p><strong>Content Safety Processing:</strong> To ensure compliance with Google Play's GenAI policies and provide a safe learning environment, we implement comprehensive content safety measures:</p>
                <ul>
                    <li><strong>User Input Validation:</strong> Your writing submissions and speaking responses are processed through AWS content safety filters to ensure educational appropriateness</li>
                    <li><strong>AI Output Validation:</strong> All AI-generated feedback and Maya examiner responses are validated for safety and educational compliance</li>
                    <li><strong>Educational Context Protection:</strong> Content is validated to ensure it relates to IELTS test preparation and maintains academic standards</li>
                    <li><strong>Safety Monitoring:</strong> We continuously monitor AI interactions to maintain a safe and appropriate learning environment</li>
                </ul>
                
                <div class="safety-highlight">
                    <strong>Important:</strong> Content safety processing is performed in real-time to protect all users. No inappropriate content is stored, and safety violations are immediately blocked and logged for compliance monitoring.
                </div>
            </div>
            
            <div class="section">
                <h3>Information We Collect</h3>
                <h4>Assessment Data</h4>
                <ul>
                    <li>Your IELTS writing submissions and speaking responses</li>
                    <li>Assessment scores and feedback generated by our AI systems</li>
                    <li>Progress tracking and performance analytics</li>
                    <li>Safety validation results and compliance metrics</li>
                </ul>
                
                <h4>TrueScore® Writing Assessment Technology</h4>
                <ul>
                    <li>Written responses to IELTS Task 1 and Task 2 prompts</li>
                    <li>AI-generated feedback on Task Achievement, Coherence & Cohesion, Lexical Resource, and Grammatical Range & Accuracy</li>
                    <li>Band score calculations and detailed improvement suggestions</li>
                    <li>Content safety validation reports</li>
                </ul>
                
                <h4>ClearScore® Speaking Assessment Technology</h4>
                <ul>
                    <li>Audio recordings of your speaking responses (processed in real-time, not stored)</li>
                    <li>Transcripts generated by Maya AI examiner for assessment purposes</li>
                    <li>Fluency, pronunciation, vocabulary, and grammar evaluations</li>
                    <li>Conversational interaction logs for assessment continuity</li>
                </ul>
            </div>
            
            <div class="section">
                <h3>How We Use Your Information</h3>
                <h4>Educational Purposes</h4>
                <ul>
                    <li>Provide personalized IELTS assessment and feedback</li>
                    <li>Track your progress and improvement over time</li>
                    <li>Generate detailed performance reports and recommendations</li>
                    <li>Ensure content safety and educational appropriateness</li>
                </ul>
                
                <h4>AI Safety and Compliance</h4>
                <ul>
                    <li>Validate content safety and educational appropriateness</li>
                    <li>Monitor AI system performance and safety metrics</li>
                    <li>Ensure compliance with Google Play GenAI policies</li>
                    <li>Maintain detailed safety and compliance documentation</li>
                </ul>
            </div>
            
            <div class="section">
                <h3>Data Protection and Security</h3>
                
                <div class="safety-highlight">
                    <strong>AI Safety Measures:</strong>
                    <ul>
                        <li>Real-time content safety filtering using AWS Comprehend</li>
                        <li>Automated blocking of inappropriate content</li>
                        <li>Educational context validation for all interactions</li>
                        <li>Comprehensive safety testing and monitoring</li>
                        <li>Incident logging and response protocols</li>
                    </ul>
                </div>
                
                <h4>Data Storage and Processing</h4>
                <ul>
                    <li>All data is encrypted in transit and at rest</li>
                    <li>Assessment data is stored securely in AWS DynamoDB</li>
                    <li>Audio recordings are processed in real-time and not permanently stored</li>
                    <li>Safety validation results are logged for compliance monitoring</li>
                </ul>
            </div>
            
            <div class="section">
                <h3>Data Sharing and Disclosure</h3>
                <p>We do not sell, trade, or otherwise transfer your personal information to third parties except:</p>
                <ul>
                    <li>For content safety processing through AWS services</li>
                    <li>To comply with legal requirements or protect our rights</li>
                    <li>With your explicit consent for specific purposes</li>
                    <li>For Google Play compliance monitoring and reporting</li>
                </ul>
            </div>
            
            <div class="section">
                <h3>Your Rights and Choices</h3>
                <ul>
                    <li>Access your personal data and assessment history</li>
                    <li>Request correction of inaccurate information</li>
                    <li>Request deletion of your data (subject to legal requirements)</li>
                    <li>Opt out of non-essential data processing</li>
                    <li>Receive information about content safety processing</li>
                </ul>
            </div>
            
            <div class="section">
                <h3>Contact Information</h3>
                <p>If you have questions about this Privacy Policy or our AI safety measures, please contact us at:</p>
                <p><strong>Email:</strong> privacy@ieltsaiprep.com</p>
                <p><strong>Subject:</strong> Privacy Policy or AI Safety Inquiry</p>
            </div>
            
            <div class="section">
                <h3>Changes to This Policy</h3>
                <p>We may update this Privacy Policy to reflect changes in our AI safety measures or legal requirements. We will notify you of any material changes by posting the updated policy on our website.</p>
            </div>
        </div>
    </div>
    
    <footer class="text-center py-4 mt-5">
        <div class="container">
            <p>&copy; 2025 IELTS GenAI Prep. All rights reserved.</p>
            <p><a href="/terms-of-service">Terms of Service</a> | <a href="/privacy-policy">Privacy Policy</a></p>
        </div>
    </footer>
</body>
</html>'''

if __name__ == "__main__":
    # Generate updated privacy policy
    updated_html = get_updated_privacy_policy_html()
    
    # Save to file
    with open('approved_privacy_policy_genai.html', 'w', encoding='utf-8') as f:
        f.write(updated_html)
    
    print("Updated privacy policy with GenAI content safety disclosures created successfully!")
    print("File saved as: approved_privacy_policy_genai.html")