# IELTS GenAI Prep - Production Configuration
# AWS Lambda Serverless Architecture with Global Deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: ielts-genai-prep-config
data:
  # Global Configuration
  APP_NAME: "IELTS GenAI Prep"
  VERSION: "2.0.0"
  STAGE: "prod"
  
  # Regional Deployment
  PRIMARY_REGION: "us-east-1"
  SECONDARY_REGIONS: "eu-west-1,ap-southeast-1"
  NOVA_SONIC_REGION: "us-east-1"
  
  # API Gateway Configuration
  CORS_ORIGIN: "https://ieltsaiprep.com"
  API_THROTTLE_RATE: "1000"
  API_BURST_LIMIT: "2000"
  
  # Database Configuration
  DYNAMODB_BILLING_MODE: "PAY_PER_REQUEST"
  DYNAMODB_BACKUP_ENABLED: "true"
  GLOBAL_TABLES_ENABLED: "true"
  
  # Cache Configuration
  ELASTICACHE_NODE_TYPE: "cache.r6g.large"
  ELASTICACHE_NUM_NODES: "2"
  ELASTICACHE_ENGINE_VERSION: "7.0"
  
  # Lambda Configuration
  LAMBDA_RUNTIME: "python3.11"
  LAMBDA_TIMEOUT: "900"
  LAMBDA_MEMORY: "3008"
  LAMBDA_PROVISIONED_CONCURRENCY: "50"
  
  # Nova Sonic Configuration
  NOVA_SONIC_MODEL: "amazon.nova-sonic-1:0"
  NOVA_MICRO_MODEL: "amazon.nova-micro-1:0"
  STREAMING_ENABLED: "true"
  BIDIRECTIONAL_AUDIO: "true"
  
  # QR Authentication Configuration
  QR_TOKEN_EXPIRATION: "600"
  QR_REFRESH_INTERVAL: "540"
  SESSION_DURATION: "3600"
  
  # Mobile App Configuration
  IOS_BUNDLE_ID: "com.ieltsaiprep.genai"
  ANDROID_PACKAGE_NAME: "com.ieltsaiprep.genai"
  APP_STORE_PRODUCT_IDS: "academic_speaking_assessment,academic_writing_assessment,general_speaking_assessment,general_writing_assessment"
  PRODUCT_PRICE_USD: "36.49"
  
  # Assessment Configuration
  ASSESSMENT_TYPES: "academic_speaking,academic_writing,general_speaking,general_writing"
  MAX_ESSAY_LENGTH: "400"
  SPEAKING_DURATION_MINUTES: "15"
  FEEDBACK_ENABLED: "true"
  
  # Security Configuration
  JWT_ALGORITHM: "HS256"
  SESSION_COOKIE_SECURE: "true"
  SESSION_COOKIE_HTTPONLY: "true"
  SESSION_COOKIE_SAMESITE: "strict"
  
  # Monitoring Configuration
  CLOUDWATCH_LOGS_ENABLED: "true"
  CLOUDWATCH_METRICS_ENABLED: "true"
  X_RAY_TRACING_ENABLED: "true"
  
  # Scaling Configuration
  AUTO_SCALING_ENABLED: "true"
  MIN_CAPACITY: "5"
  MAX_CAPACITY: "1000"
  TARGET_UTILIZATION: "70"

---
# Regional Endpoint Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ielts-genai-prep-endpoints
data:
  # API Gateway Endpoints
  API_US_EAST_1: "https://api-us.ieltsaiprep.com"
  API_EU_WEST_1: "https://api-eu.ieltsaiprep.com"
  API_AP_SOUTHEAST_1: "https://api-ap.ieltsaiprep.com"
  
  # WebSocket Endpoints
  WEBSOCKET_US_EAST_1: "wss://streaming-us.ieltsaiprep.com"
  WEBSOCKET_EU_WEST_1: "wss://streaming-eu.ieltsaiprep.com"
  WEBSOCKET_AP_SOUTHEAST_1: "wss://streaming-ap.ieltsaiprep.com"
  
  # Nova Sonic Streaming (US East 1 only)
  NOVA_SONIC_ENDPOINT: "wss://streaming-us.ieltsaiprep.com/nova-sonic"
  
  # CDN Endpoints
  CDN_US: "https://cdn-us.ieltsaiprep.com"
  CDN_EU: "https://cdn-eu.ieltsaiprep.com"
  CDN_AP: "https://cdn-ap.ieltsaiprep.com"

---
# DynamoDB Table Definitions
apiVersion: v1
kind: ConfigMap
metadata:
  name: ielts-genai-prep-tables
data:
  # Core Tables
  QR_TOKENS_TABLE: "ielts-genai-prep-qr-tokens-prod"
  SESSIONS_TABLE: "ielts-genai-prep-sessions-prod"
  ASSESSMENTS_TABLE: "ielts-genai-prep-assessments-prod"
  USERS_TABLE: "ielts-genai-prep-users-prod"
  PURCHASES_TABLE: "ielts-genai-prep-purchases-prod"
  
  # Index Configurations
  USER_EMAIL_INDEX: "user-email-index"
  SESSION_ID_INDEX: "session-id-index"
  ASSESSMENT_TYPE_INDEX: "assessment-type-index"
  PURCHASE_STATUS_INDEX: "purchase-status-index"
  
  # TTL Configuration
  QR_TOKENS_TTL_ATTRIBUTE: "expires_at"
  SESSIONS_TTL_ATTRIBUTE: "expires_at"
  
  # Global Table Regions
  GLOBAL_TABLE_REGIONS: "us-east-1,eu-west-1,ap-southeast-1"

---
# Lambda Function Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ielts-genai-prep-functions
data:
  # Core Functions
  AUTH_FUNCTION: "ielts-genai-prep-prod-auth"
  ASSESSMENT_FUNCTION: "ielts-genai-prep-prod-assessment"
  STREAMING_FUNCTION: "ielts-genai-prep-prod-streaming"
  PURCHASE_FUNCTION: "ielts-genai-prep-prod-purchase"
  QR_FUNCTION: "ielts-genai-prep-prod-qr"
  
  # WebSocket Functions
  WEBSOCKET_CONNECT: "ielts-genai-prep-prod-ws-connect"
  WEBSOCKET_DISCONNECT: "ielts-genai-prep-prod-ws-disconnect"
  WEBSOCKET_MESSAGE: "ielts-genai-prep-prod-ws-message"
  
  # Background Functions
  CLEANUP_FUNCTION: "ielts-genai-prep-prod-cleanup"
  MIGRATION_FUNCTION: "ielts-genai-prep-prod-migrate"
  BACKUP_FUNCTION: "ielts-genai-prep-prod-backup"

---
# Environment Variables for Lambda Functions
apiVersion: v1
kind: Secret
metadata:
  name: ielts-genai-prep-secrets
type: Opaque
data:
  # Note: Values should be base64 encoded in actual deployment
  JWT_SECRET: "your-jwt-secret-key"
  ENCRYPTION_KEY: "your-encryption-key"
  WEBHOOK_SECRET: "your-webhook-secret"
  
  # Apple App Store Configuration
  APPLE_SHARED_SECRET: "your-apple-shared-secret"
  APPLE_TEAM_ID: "your-apple-team-id"
  APPLE_KEY_ID: "your-apple-key-id"
  APPLE_PRIVATE_KEY: "your-apple-private-key"
  
  # Google Play Store Configuration
  GOOGLE_SERVICE_ACCOUNT_KEY: "your-google-service-account-key"
  GOOGLE_PACKAGE_NAME: "com.ieltsaiprep.genai"
  
  # Third-party Integrations
  STRIPE_SECRET_KEY: "your-stripe-secret-key"
  SENDGRID_API_KEY: "your-sendgrid-api-key"
  ANALYTICS_API_KEY: "your-analytics-api-key"

---
# CloudWatch Monitoring Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ielts-genai-prep-monitoring
data:
  # Log Groups
  API_LOG_GROUP: "/aws/lambda/ielts-genai-prep-prod-api"
  STREAMING_LOG_GROUP: "/aws/lambda/ielts-genai-prep-prod-streaming"
  
  # Metric Filters
  ERROR_METRIC_FILTER: "ERROR"
  LATENCY_METRIC_FILTER: "LATENCY"
  
  # Alarms
  HIGH_ERROR_RATE_THRESHOLD: "10"
  HIGH_LATENCY_THRESHOLD: "5000"
  LOW_SUCCESS_RATE_THRESHOLD: "95"
  
  # Dashboard Configuration
  DASHBOARD_NAME: "IELTSGenAIPrep-Production"
  DASHBOARD_REGION: "us-east-1"
  
  # Log Retention
  LOG_RETENTION_DAYS: "30"
  METRIC_RETENTION_DAYS: "90"

---
# Auto Scaling Configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: ielts-genai-prep-scaling
data:
  # Lambda Scaling
  LAMBDA_CONCURRENT_EXECUTIONS: "1000"
  LAMBDA_PROVISIONED_CONCURRENCY: "50"
  
  # DynamoDB Scaling
  DYNAMODB_READ_CAPACITY_MIN: "5"
  DYNAMODB_READ_CAPACITY_MAX: "40000"
  DYNAMODB_WRITE_CAPACITY_MIN: "5"
  DYNAMODB_WRITE_CAPACITY_MAX: "40000"
  
  # ElastiCache Scaling
  ELASTICACHE_MIN_REPLICAS: "1"
  ELASTICACHE_MAX_REPLICAS: "5"
  
  # API Gateway Scaling
  API_GATEWAY_THROTTLE_RATE: "1000"
  API_GATEWAY_BURST_LIMIT: "2000"
  
  # Scaling Policies
  SCALE_UP_THRESHOLD: "80"
  SCALE_DOWN_THRESHOLD: "20"
  SCALE_UP_COOLDOWN: "300"
  SCALE_DOWN_COOLDOWN: "300"

---
# Backup and Disaster Recovery
apiVersion: v1
kind: ConfigMap
metadata:
  name: ielts-genai-prep-backup
data:
  # Backup Configuration
  BACKUP_ENABLED: "true"
  BACKUP_RETENTION_DAYS: "35"
  POINT_IN_TIME_RECOVERY: "true"
  
  # Cross-Region Backup
  BACKUP_DESTINATION_REGIONS: "us-west-2,eu-central-1"
  
  # Recovery Configuration
  RTO_TARGET_MINUTES: "60"
  RPO_TARGET_MINUTES: "15"
  
  # Backup Schedule
  DAILY_BACKUP_TIME: "03:00 UTC"
  WEEKLY_BACKUP_DAY: "sunday"
  MONTHLY_BACKUP_DATE: "1"