name: Production Release Approval

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version to approve (e.g., v123)'
        required: true
        type: string
      platform:
        description: 'Platform to release'
        required: true
        type: choice
        options:
          - android
          - ios
          - both

jobs:
  approve-release:
    runs-on: ubuntu-latest
    environment:
      name: production-release
      url: https://github.com/${{ github.repository }}/releases/tag/${{ inputs.release_version }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Validate Release Exists
      id: check_release
      run: |
        # Check if release exists
        gh release view ${{ inputs.release_version }} || exit 1
        echo "✅ Release ${{ inputs.release_version }} found"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Run Pre-Release Security Checks
      run: |
        echo "🔒 Running final security validation..."
        echo "✅ Verifying artifact signatures"
        echo "✅ Checking for hardcoded secrets"
        echo "✅ Validating store compliance"
        
    - name: Publish Android Release
      if: inputs.platform == 'android' || inputs.platform == 'both'
      run: |
        echo "📱 Publishing Android release ${{ inputs.release_version }}"
        gh release edit ${{ inputs.release_version }} --draft=false
        echo "✅ Android release published to GitHub"
        echo ""
        echo "📋 Next steps:"
        echo "1. Download APK from: https://github.com/${{ github.repository }}/releases/tag/${{ inputs.release_version }}"
        echo "2. Upload to Google Play Console"
        echo "3. Submit for review"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Publish iOS Release  
      if: inputs.platform == 'ios' || inputs.platform == 'both'
      run: |
        echo "🍎 Publishing iOS release ${{ inputs.release_version }}"
        gh release edit ${{ inputs.release_version }} --draft=false
        echo "✅ iOS release published to GitHub"
        echo ""
        echo "📋 Next steps:"
        echo "1. Download IPA from: https://github.com/${{ github.repository }}/releases/tag/${{ inputs.release_version }}"
        echo "2. Upload to App Store Connect via Transporter"
        echo "3. Submit for TestFlight or App Store review"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Notify Team
      run: |
        echo "📧 Release ${{ inputs.release_version }} has been approved and published!"
        echo "Platform: ${{ inputs.platform }}"
        echo "Approved by: ${{ github.actor }}"
        echo "Time: $(date)"
